### ISSUE TITLE
Keystone support in BMI

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ims#127]
We really need BMI to support keystone authentication. This came up in a conversation I was having with @chemistry-sourabh. Since I'll be upgrading one of our production environment HILs to use keystone authentication, BMI would no longer work in that environment. 

@apoorvemohan @pgrosu

**Comment by apoorvemohan** [comment]
why do you think BMI won't work?

**Comment by chemistry-sourabh** [comment]
@apoorvemohan if hil uses keystone then it will only accept keystone auth and deny regular auth. @ravisantoshgudimetla wanted me to implement keystone way back, but hil wasnt ready so I left certain functions which can updated to implement keystone.

**Comment by apoorvemohan** [comment]
In the future, we want to decouple network isolation operations from BMI (All the network isolation operations must be handled by the user.) I for now I am not sure what is the right thing to do. Adding support for keystone auth (because HIL requires it) seems like a throwaway work to me.

**Comment by chemistry-sourabh** [comment]
Did @ravisantoshgudimetla agree about separating the network isolation operations ?

The simplest way I would say is to make a mock hil driver and use that instead of the actual one. It is simpler than removing all the hil calls and incase users want to use the actual hil driver they can.

**Comment by apoorvemohan** [comment]
Since you guys left there are new requirements to BMI. Initlally when BMI was designed, the requirement was to have it only in a multi-tenant environment where it is always running on top on HIL. But now things have changed. BMI is required to be a provisioning and image management system for both multi-tenant and standalone environments (flat networks) and should be able to use different network isolation layers underneath it (and should not at all be tightly coupled with HIL). Also, all the network isolation operations should not be done by BMI. HIL and BMI are two separate pieces and should not depend on each other. 

@naved001 did you committed the new design specs somewhere?

**Comment by naved001** [comment]
@apoorvemohan I don't have a detailed specs, but notes from our design specifications.

> # BMI Design:
> 
> Simply put, we want to make BMI just like libvirt but for bare metal clouds.
> 
> 1. We want user to setup the network rather than BMI making a call to the
> network isolator. To achieve, this we would need to get rid of all calls to any
> network isolator in the code (right now, it's HIL hardcoded).
> 
> Some of the API calls would look like this:
> 
> ## List Images:
> It would be a GET call that reads from the database.
> 
> ## Provision:
> 
> ("provision/", 'PUT', IMG_NAME, INTERFACE_NAME, MAC_ADDR, AUTH_TOKEN).
> 
> ## Deprovision:
> 
> ("dpro/", 'DELETE', MAC_ADDR, AUTH_TOKEN)
> 
> ## Create Snapshots:
> 
> ("snapshot_create/", 'PUT', NODE_NAME, SNAP_NAME, AUTH_TOKEN)
> 
> ## List Snapshots:
> 
> A get call which should have AUTH_TOKEN
> 
> ## Upload Image:
> 
> ("upload/", 'PUT', IMAGE_NAME, AUTH_TOKEN)
> 
> ## Remove Image:
> 
> ('DELETE', IMG_NAME, AUTH_TOKEN)
> 
> ## Snapshot:
> 
> Node should be off when snapshotting.
> 
> -> We should set the iSCSI target offtime and then snapshot. Otherwise it will
> complain saying target is busy.
> 
> Paramters required MAC_ADDR, SNAP_NAME, and AUTH_TOKEN
> 
> ## Clone Images:
> 
> ('PUT', SOURCE_IMAGE, DEST_IMAGE, AUTH_TOKEN)
> 
> Pass an optional argument to flatten an image. By default, make linked clones.
> 
> ## Upload Image:
> 
> ('PUT', IMAGE_NAME, AUTH_TOKEN, PATH TO IMAGE)

**Comment by chemistry-sourabh** [comment]
So if I understand BMI wont have a network isolator anymore. In that case we better remove all the HIL calls. All of them are in operations.py anyways, but I guess this wont be done in 0.5 ?

**Comment by apoorvemohan** [comment]
Here is a primary architecture diagram:

<img width="1680" alt="screen shot 2017-06-22 at 10 45 48 am" src="https://user-images.githubusercontent.com/3013622/27440329-5fbfdfc4-5738-11e7-80f3-2e7308eb29d5.png">

**Comment by chemistry-sourabh** [comment]
Got it. So implementing Keystone will be tougher now. We thought of just passing the keystone token to HIL initially.

The right way to do it is to remove every HIL call which should be easy as they are in operations.py only. You want a temp simple solution then mock out the hil object in operations.py

I would do the first one as it is just one file. The question is when should we do it ? We will lose BMI-prod when @naved001 updates HIL.

**Comment by apoorvemohan** [comment]
@naved001 is there an urgent requirement for HIL to use keystone auth?

**Comment by pgrosu** [comment]
@naved001, @apoorvemohan  We might all need to sit down and rehash this to add more operational details.  Not sure why use `PUT` method in the tuple, but I'm assuming most of these will `POST` requests.  Also images require transformation so that they go on the appropriate store (i.e. I'm not sure an we just transfer an ISO, but want to make a bootable image for our nodes).  We could make that transformation seamless via things such as RedHat Kickstart Installation or other means, but that requires we have those processes in place.

Though BMI uses it, cloning is not a BMI feature but a storage service feature.  Therefore you would need a REST service around your `Data Store`.  Thus authentication is tied to a resource such as the storage not BMI.  Again this is a level of functional purity that we could still implement, as each object on Ceph has metadata.  Usually the metadata service is not tied to the same resource (i.e. object store) but in this case we are lucky :)

@chemistry-sourabh Yes we want to keep the functionality pure in BMI, so network isolation is a HIL feature that BMI will depend on - and most likely in the next version.

To simplify the problem let's first research scenarios and test them out before making them a requirement.  Then we can properly plan them for delivery for the next version.

**Comment by naved001** [comment]
@apoorvemohan, Jason (@henn) suggested that we use keystone in kaizen since it would simplify authentication (compared to db auth) and so that we can internally test it. 

There seems to be no hard/urgent requirement to use keystone. 

And I agree with you that it might be throwaway work if we plan to drop support for network isolation from BMI. But if we were to support HIL, then we should support keystone. 

@pgrosu

> Though BMI uses it, cloning is not a BMI feature but a storage service feature. Therefore you would need a REST service around your Data Store. Thus authentication is tied to a resource such as the storage not BMI.

BMI exposes the storage service features. so BMI authenticates with the storage backend (in case of ceph, we have that keyring file for auth), and the user authenticate with BMI using whatever mechanism we want (for instance, db auth or keystone). So why would we need a REST service around storage?

**Comment by pgrosu** [comment]
@naved001 You want to have as few authentication mechanisms.  Basically you really just want a single sign-on.

**Comment by apoorvemohan** [comment]
@naved001 Can we postpone the use of Keystone until BMI is re-designed? Can you talk to Jason about this?

**Comment by chemistry-sourabh** [comment]
or @naved001  is there a way to make keystone auth optional, then you can upgrade and we can continue using the db auth

**Comment by ravisantoshgudimetla** [comment]
Apologies if I am joining the conversation late. But, can @apoorvemohan or @naved001 explain what is going to happen in provision call. I am curious about the approach.

> The right way to do it is to remove every HIL call which should be easy as they are in operations.py only. You want a temp simple solution then mock out the hil object in operations.py

So, HIL is supposed to do a network isolation, if we want to take the calls out of BMI for attaching, we need to build something external to both HIL and BMI which orchestrates. Without that, it looks like we are headed towards that some sort of throwaway work. 

One more point that I want to make this, if we don't rely on HIL/some network isolator for projects in BMI, we need to make sure that we sync the projects in HIL/network isolator with BMI. I think @pgrosu made a valid point, that we need to hash out details before proceeding further. TBH, I think this needs a larger discussion as we are trying to move away from some underlying assumptions that BMI has been built on top of.

**Comment by chemistry-sourabh** [comment]
No @ravisantoshgudimetla you are very early :P 

But I think all of us should meet some weekend to discuss this in greater detail. Also this is one of the requests in #129

**Comment by apoorvemohan** [comment]
closing this issue and starting a separate re-designing thread
